base_calibration_node:
  ros__parameters:
    verbose: true
    calibration_steps:
      - slow_rollout_back
      - slow_rollout_forward
      - slow_spin_left
      - slow_spin_right
      - fast_spin_left
      - fast_spin_right
    slow_rollout_back:
      type: rollout
      velocity: -0.2
      distance: -1.0
    slow_rollout_forward:
      type: rollout
      velocity: 0.2
      distance: 1.0
    slow_spin_left:
      type: spin
      velocity: 0.5
      rotations: 1
    slow_spin_right:
      type: spin
      velocity: -0.5
      rotations: 1
    fast_spin_left:
      type: spin
      velocity: 1.5
      rotations: 1
    fast_spin_right:
      type: spin
      velocity: -1.5
      rotations: 1
