robot_calibration:
  ros__parameters:
    chains:
    - arm
    - head
    arm:
      topic: /arm_controller/follow_joint_trajectory
      joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      #planning_group: arm TODO: revert when moveit is setup
    head:
      topic: /head_controller/follow_joint_trajectory
      joints:
      - head_pan_joint
      - head_tilt_joint
    features:
    - led_finder
    led_finder:
      type: robot_calibration/LedFinder
      action: /gripper_controller/led_command
      topic: /head_camera/depth_registered/points
      camera_sensor_name: camera
      chain_sensor_name: arm
      threshold: 500.0
      max_iterations: 25
      debug_image: false
      gripper_led_frame: wrist_roll_link
      leds:
      - led1
      - led2
      - led3
      - led4
      led1:
        code: 1
        topic: led1
        x: 0.0621
        y: 0.023
        z: 0.026875
      led2:
        code: 2
        topic: led2
        x: 0.027
        y: 0.023
        z: 0.026875
      led3:
        code: 4
        topic: led3
        x: 0.061
        y: -0.023
        z: 0.026875
      led4:
        code: 8
        topic: led4
        x: 0.027
        y: -0.023
        z: 0.026875
