uint64  stamp

uint8 charger_state
uint8 charger_error
uint8 charger_error_state
uint8 charger_last_error
uint8 current_limit_cause
uint8 battery_balance_state
uint8 supply_input
uint8 charging_mode
uint16 charger_error_count

float32 system_voltage
float32 battery_bot_voltage
float32 battery_top_voltage
float32 dock_voltage
float32 plug_voltage
float32 charging_voltage
float32 battery_temperature
float32 charger_temperature
float32 battery_current
float32 charger_current
float32 supply_current
float32 system_current
float32 charge_remaining
float32 runtime_remaining
float32 fan_speed

float32 duty_a
float32 duty_b

string[] degug_names
float32[] debug_values
