sensors: ["head_camera"]
head_camera:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  far_clipping_plane_distance: 5.0
  filtered_cloud_topic: ""
  image_topic: /head_camera/depth_downsample/image_raw
  max_update_rate: 5.0
  near_clipping_plane_distance: 0.0
  padding_offset: 0.0
  padding_scale: 0.0
  queue_size: 1
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.0