sensors:
  - far_clipping_plane_distance: 10
    filtered_cloud_topic: ""
    image_topic: /head_camera/depth_downsample/image
    max_update_rate: ""
    near_clipping_plane_distance: 0
    padding_offset: ""
    padding_scale: ""
    queue_size: 1
    sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    shadow_threshold: ""